### ISSUE TITLE
attempt to index local 'info' (a nil value)

### ISSUE THREAD

**Issue by verymilan** [octacian/chat3#3]
Hi, my server randomly crashes in 

`chat3/init.lua:170: in function <chat3/init.lua:167>`

I sadly don't know how to resolve it myself.. :/

**Comment by verymilan** [comment]
Is this mod abandoned?

**Comment by octacian** [comment]
> Is this mod abandoned?

Sort of. I'm inactive in the MT community at this point for a number of reasons, so I'm quite slow to deal with issues in my mods.

But anyways, this issue for one should be fixed. I'm not entirely certain though, as I couldn't manage to recreate the error myself so I'm just theorizing. If it does come up again, please let me know (probably here, but a new issue is fine too).

I apologize for any inconveniences my delay in fixing this has caused.

**Comment by verymilan** [comment]
Great, thanks for clarifying and the bugfix-attempt, i will report back. :)
